### ISSUE TITLE
Make cards for mentors.

### ISSUE THREAD

**Issue by Ace-Bansal** [opencodeiiita/Opencode-Collaborative-19#16] opened 2019-01-12 08:10 UTC
The mentors should be displayed in separate cards.
![cards](https://user-images.githubusercontent.com/34866483/51070932-8defe180-166f-11e9-82ce-2f4f575e698f.jpg)
Take a look at these cards for reference.
You may use use Bootstrap 4 cards.

**Comment by mohammed-adil** [comment] 2019-01-12 10:18
@opencodebot claim

**Comment by parag1201** [comment] 2019-01-12 10:31
@opencodebot claim

**Comment by Ace-Bansal** [comment] 2019-01-12 10:36
@mohammed-adil already has an issue assigned to him. @nucelya this one's been assigned to you.

**Comment by orichamaru** [comment] 2019-01-15 09:00
@opencodebot claim

**Comment by orichamaru** [comment] 2019-01-15 09:17
@opencodebot

**Comment by orichamaru** [comment] 2019-01-15 09:18
@opencodebot claim

**Comment by helios1101** [comment] 2019-01-18 13:19
Is this issue fixed? Can I work on this issue?
@opencodebot claim

**Comment by helios1101** [comment] 2019-01-19 15:00
@Ace-Bansal  Can I try this issue?

**Comment by anupm12** [comment] 2019-01-22 12:30
@Ace-Bansal can you assign this issue to me?

**Comment by sourabh1031** [comment] 2019-01-25 05:10
@prateek76 i will take this issue

**Comment by ananya-agrawal** [comment] 2019-01-28 19:19
Closing this issue for now as the issue is not clear about what to do

**Closed by ananya-agrawal** 2019-01-28 19:19 UTC
Labels: OpenCode19, Skilled: 20 points
